FROM php:fpm
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt pdo pdo_mysql mbstring  \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
RUN apt-get install -y \
        libmagickwand-dev \
        imagemagick \
    && pecl install imagick-3.4.1 \
    && docker-php-ext-enable imagick
RUN pear install HTTP_WebDAV_Server-1.0.0RC8 \ 
    && pear install Log
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('SHA384', 'composer-setup.php') === 'aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer
RUN docker-php-ext-install -j$(nproc) zip
RUN pear channel-discover pear.dotkernel.com/zf1/svn \
    && pear install zend/zend
RUN pear install Mail
RUN apt-get install -y \
        poppler-utils \
        catdoc \
        gnumeric \
        id3
RUN apt-get install -y \
        cron

CMD ["sh", "-c", "cron && php-fpm"]
